---
# Configures SSH daemon

- name: Ensure only SSH version 2 is allowed
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^Protocol"
              line="Protocol 2"
              state=present
  notify: restart sshd
  tags: sshd

- name: Ensure we are using privilege separation for SSH
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^UsePrivilegeSeparation"
              line="UsePrivilegeSeparation yes"
              state=present
  notify: restart sshd
  tags: sshd

- name: Ensure we are using strict modes for SSH
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^StrictModes"
              line="StrictModes yes"
              state=present
  notify: restart sshd
  tags: sshd

- name: Ensure empty passwords are not allowed for SSH
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitEmptyPasswords"
              line="PermitEmptyPasswords no"
              state=present
  notify: restart sshd
  tags: sshd

- name: Ensure we print information about the users last SSH login
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PrintLastLog"
              line="PrintLastLog yes"
              state=present
  notify: restart sshd
  tags: sshd

- name: Disallow password authentication for SSH
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart sshd
  tags: sshd

- name: Disallow SSH access for root user
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: restart sshd
  tags: sshd

- name: Disable DebianBanner announcement
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^DebianBanner"
              line="DebianBanner no"
              state=present
  notify: restart sshd
  tags: sshd

- name: Disable using .rhosts for SSH authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^IgnoreRhosts"
              line="IgnoreRhosts yes"
              state=present
  notify: restart sshd
  tags: sshd

- name: Disable host based authentication for SSH
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^HostbasedAuthentication"
              line="HostbasedAuthentication no"
              state=present
  notify: restart sshd
  tags: sshd

- name: Divert original /etc/issue.net
  command: dpkg-divert --quiet --local --divert /etc/issue.net.dpkg-divert --rename /etc/issue.net
           creates=/etc/issue.net.dpkg-divert
  tags: sshd

- name: Ensure the /etc/issue.net file is correct
  copy: src=issue.net
        dest=/etc/issue.net
        owner=root
        group=root
        mode=0644

- name: Ensure SSH shows /etc/issue.net as the banner
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^Banner"
              line="Banner /etc/issue.net"
              state=present
  notify: restart sshd
  tags: sshd
