---
# This playbook configures an Nginx web server

- name: Ensure Nginx apt repository key is present
  apt_key: id=7BD9BF62
           url=http://nginx.org/keys/nginx_signing.key
           state=present

- name: Ensure Nginx apt repository is present
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ trusty nginx'
                  state=present

- name: Ensure Nginx is installed
  apt: pkg={{ item }}
       state=present
       update_cache=yes
       cache_valid_time=3600
  with_items:
    - nginx
    - python-passlib

- name: Ensure Nginx service enabled status is set to {{ start_nginx_at_boot }} value
  service: name=nginx enabled={{ start_nginx_at_boot }}

- name: Divert original /etc/nginx/conf.d/default.conf
  command: dpkg-divert --quiet --local --divert /etc/nginx/conf.d/default.conf.dpkg-divert --rename /etc/nginx/conf.d/default.conf
           creates=/etc/nginx/conf.d/default.conf.dpkg-divert

- name: Ensure Nginx default configuration is present
  template: src=default.conf.j2
            dest=/etc/nginx/conf.d/default.conf
            owner=root
            group=root
            mode=0644
  notify: test nginx and reload

- name: Ensure the Nginx example_ssl.conf file is not present
  file: path=/etc/nginx/conf.d/example_ssl.conf
        state=absent
  notify: test nginx and reload