---
# This contains all handlers used in the common role

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart ntpd
  service: name=ntp state=restarted
  tags: ntpd

- name: restart sshd
  service: name=ssh state=restarted
  tags: sshd

- name: clean apt caches
  command: apt-get clean

- name: clean tmp directory
  command: rm -rf /tmp/*

- name: clean DHCP leases
  command: rm -f /var/lib/dhcp/*

- name: clean unneeded packages
  command: apt-get -y autoremove
